<div class="hero-unit span8 offset1">
	<img class="pull-right" src="/img/1342186398_delivery.png">
	<h1>Witaj w TranSys,</h1>
	<p>nowatorskiej i wspaniałej firmie kurierskiej, której jedynym celem jest satysfackja klienta!</p>
	<p>Nasz cel osiągamy poprzez kilka prostych kroków:</p> 
	<ul>
		<li><h3>Łatwe zlecanie zadań</h3></li>
		<li><h3>Szybkość działania</h3></li>
		<li><h3>Bezproblemową obsługę</h3></li>
		<li><h3>Zadowolenie klienta</h3></li>
	</ul>
	<p>&nbsp;</p>
	<div class="pull-right">
		<p>Więc nie czekaj! Skorzystaj z naszych usług już teraz!</p>
		<p><a href="/package/new" class="btn btn-primary btn-large">Utwórz nowe zlecenie</a>
	</div>
</div>