<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>TranSys</title>
<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/bootstrap.min.js"></script>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('.navbar .brand').dblclick(function(){
		location.href='/admin';
	});
});
</script>
<link href="/css/bootstrap.css" rel="stylesheet">
<style type="text/css">
body {
    padding-top: 60px;
    padding-bottom: 40px;
    line-height: 1.7em;
}

.navbar-fixed-top .brand {
	padding-right: 0;
	padding-left: 0;
	margin-left: 20px;
	font-weight: bold;
	color: white;
	text-shadow: 0 1px 0 rgba(255, 255, 255, .1), 0 0 30px rgba(255, 255, 255, .125);
	-webkit-transition: all .2s linear;
	-moz-transition: all .2s linear;
	transition: all .2s linear;
}
.navbar-search.form-inline {
	margin-top: 0px;
}
.navbar-search.form-inline .input-append .btn {
	margin-left: 0px;
}
.sidebar-nav {
    padding: 9px 0;
}

article header {
	font-size: 2em;
	font-weight: bold;
	margin: 10px 0;
}
.form-horizontal .form-actions {
	text-align: center;
	padding-left: 0;
}
</style>
</head>

<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <div class="nav-collapse">
                	<a class="brand" href="/">TranSys</a>
                    <ul class="nav">
                        <li class="<?php echo App_Request::getInstance()->getController() == 'default' && App_Request::getInstance()->getAction() == 'news' ? ' active' : ''; ?>"><a href="/default/news">Aktualności</a></li>
                        <li class="<?php echo App_Request::getInstance()->getController() == 'package' && App_Request::getInstance()->getAction() == 'new' ? ' active' : ''; ?>"><a href="/package/new">Nowe zlecenie</a></li>
                        <li class="<?php echo App_Request::getInstance()->getController() == 'package' && App_Request::getInstance()->getAction() == 'track' ? ' active' : ''; ?>"><a href="/package/track">Śledzenie przesyłki</a></li>
                    </ul>
                    <form class="navbar-search form-inline" method="get" action="/package/track">
                    	<div class="input-append">
                    		<input 
                    			type="text" 
                    			name="tracking_code" 
                    			class="search-query span3" 
                    			placeholder="Numer przesyłki" 
                    			value="<?php echo App_Request::getInstance()->getParam('tracking_code', ''); ?>"
                    		><button class="btn btn-inverse" type="submit"><i class="icon-search icon-white"></i></button>
                    	</div>
                    </form>
                </div><!--/.nav-collapse -->
                
            </div>
        </div>
    </div>
    <div class="container">
		<?php echo $content; ?>
	</div>
	<div class="container">
		<footer style="margin-top: 40px;" class="pull-right">
			&copy; 2012 Jakub Pastuszek, Adrian Piotrowicz
		</footer>
	</div>
</body>

</html>