<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<title>TranSys</title>
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/bootstrap.min.js"></script>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('.navbar .brand').dblclick(function(){
		location.href='/admin';
	});
});
</script>
<link href="/css/bootstrap.min.css" rel="stylesheet">
<link href="/css/bootstrap-responsive.min.css" rel="stylesheet">
<link href="/css/bootstrap-overrides.min.css" rel="stylesheet">
</head>

<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <div class="nav-collapse">
                	<a class="brand" href="/">TranSys</a>
                    <ul class="nav">
                        <li class="<?php echo App_Request::getInstance()->getController() == 'default' && App_Request::getInstance()->getAction() == 'news' ? ' active' : ''; ?>"><a href="/default/news">Aktualności</a></li>
                        <li class="<?php echo App_Request::getInstance()->getController() == 'package' && App_Request::getInstance()->getAction() == 'new' ? ' active' : ''; ?>"><a href="/package/new">Nowe zlecenie</a></li>
                        <li class="<?php echo App_Request::getInstance()->getController() == 'package' && App_Request::getInstance()->getAction() == 'track' ? ' active' : ''; ?>"><a href="/package/track">Śledzenie przesyłki</a></li>
                    </ul>
                    <form class="navbar-search form-inline" method="get" action="/package/track">
                    	<div class="input-append">
                    		<input 
                    			type="text" 
                    			name="tracking_code" 
                    			class="search-query span3" 
                    			placeholder="Numer przesyłki" 
                    			value="<?php echo App_Request::getInstance()->getParam('tracking_code', ''); ?>"
                    		><button class="btn btn-inverse" type="submit"><i class="icon-search icon-white"></i></button>
                    	</div>
                    </form>
                </div><!--/.nav-collapse -->
                
            </div>
        </div>
    </div>
    <div class="container">
		<?php echo $content; ?>
	</div>
	<div class="container">
		<footer style="margin-top: 40px;" class="pull-right">
			&copy; 2012 Jakub Pastuszek, Adrian Piotrowicz
		</footer>
	</div>
</body>

</html>