<table class="table table-striped table-bordered">
<tbody>
	<tr>
		<th>Liczba kurierów w systemie</th>
		<td><?php echo $this->couriers; ?></td>
	</tr>
	<tr>
		<th>Liczba administratorów w systemie</th>
		<td><?php echo $this->admins; ?></td>
	</tr>
	<tr>
		<td colspan="2">&nbsp;</td>
	</tr>
	<tr>
		<th>Liczba klientów w systemie</th>
		<td><?php echo $this->clients; ?></td>
	</tr>
	<tr>
		<td colspan="2">&nbsp;</td>
	</tr>
	<tr>
		<th>Liczba zleceń w systemie</th>
		<td><?php echo $this->packages_total; ?></td>
	</tr>
	<tr>
		<th>Liczba nowych zleceń w systemie</th>
		<td><?php echo $this->packages_new; ?></td>
	</tr>
	<tr>
		<th>Liczba ukończonych zleceń w systemie</th>
		<td><?php echo $this->packages_delivered; ?></td>
	</tr>
</tbody>
</table>

